const states = [
  { zagreb: "zagreb" },
  { "pozesko-slavonska": "požeško-slavonska" },
  { "viroviticko-podravska": "virovitičko-podravska" },
  { "bjelovarsko-bilogorska": "bjelovarsko-bilogorska" },
  { "primorsko-goranska": "primorsko-goranska" },
  { istra: "istra" },
  { "brodsko-posavska": "brodsko-posavska" },
  { "dubrovacko-neretvanska": "dubrovačko-neretvanska" },
  { karlovacka: "karlovačka" },
  { "koprivnicko-krizevacka": "koprivničko-križevačka" },
  { "krapinsko-zagorska": "krapinsko-zagorska" },
  { "licko-senjska": "ličko-senjska" },
  { medimurje: "međimurje" },
  { "osjecko-baranjska": "osječko-baranjska" },
  { "sisacko-moslavacka": "sisačko-moslavačka" },
  { "splitsko-dalmatinska": "splitsko-dalmatinska" },
  { "sibensko-kninska": "šibensko-kninska" },
  { varazdinska: "varaždinska" },
  { "vukovarsko-srijemska": "vukovarsko-srijemska" },
  { zadarska: "zadarska" },
  { zagrebacka: "zagrebačka" },
];

export function rename(state) {}
