export const states = [
    { url: "grad-zagreb", name: "grad zagreb" },
    { url: "pozesko-slavonska", name: "požeško-slavonska" },
    { url: "viroviticko-podravska", name: "virovitičko-podravska" },
    { url: "bjelovarsko-bilogorska", name: "bjelovarsko-bilogorska" },
    { url: "primorsko-goranska", name: "primorsko-goranska" },
    { url: "istarska", name: "istarska" },
    { url: "brodsko-posavska", name: "brodsko-posavska" },
    { url: "dubrovacko-neretvanska", name: "dubrovačko-neretvanska" },
    { url: "karlovacka", name: "karlovačka" },
    { url: "koprivnicko-krizevacka", name: "koprivničko-križevačka" },
    { url: "krapinsko-zagorska", name: "krapinsko-zagorska" },
    { url: "licko-senjska", name: "ličko-senjska" },
    { url: "medimurska", name: "međimurska" },
    { url: "osjecko-baranjska", name: "osječko-baranjska" },
    { url: "sisacko-moslavacka", name: "sisačko-moslavačka" },
    { url: "splitsko-dalmatinska", name: "splitsko-dalmatinska" },
    { url: "sibensko-kninska", name: "šibensko-kninska" },
    { url: "varazdinska", name: "varaždinska" },
    { url: "vukovarsko-srijemska", name: "vukovarsko-srijemska" },
    { url: "zadarska", name: "zadarska" },
    { url: "zagrebacka", name: "zagrebačka" },
  ];